
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi.logic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int AND = 12;
  public static final int ELSE = 20;
  public static final int SEMICOLON = 10;
  public static final int OR = 13;
  public static final int RBRACE = 9;
  public static final int RPAREN = 7;
  public static final int WHILE = 21;
  public static final int BOOLEAN_LITERAL = 33;
  public static final int RETURN = 26;
  public static final int GREATER = 16;
  public static final int IF = 19;
  public static final int LPAREN = 6;
  public static final int LBRACE = 8;
  public static final int ID = 34;
  public static final int STRING_LITERAL = 31;
  public static final int BOOLEAN = 30;
  public static final int STRING = 29;
  public static final int EQUALS = 11;
  public static final int SUB_PROGRAM = 25;
  public static final int EOF = 0;
  public static final int MAIN = 18;
  public static final int BREAK = 22;
  public static final int DIV = 5;
  public static final int ADD = 2;
  public static final int PUTW = 23;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int PUTS = 24;
  public static final int ASSIGN = 17;
  public static final int INTEGER_LITERAL = 32;
  public static final int INTEGER = 28;
  public static final int NULL = 27;
  public static final int LESS = 15;
  public static final int DIF = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "MINUS",
  "TIMES",
  "DIV",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "EQUALS",
  "AND",
  "OR",
  "DIF",
  "LESS",
  "GREATER",
  "ASSIGN",
  "MAIN",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "PUTW",
  "PUTS",
  "SUB_PROGRAM",
  "RETURN",
  "NULL",
  "INTEGER",
  "STRING",
  "BOOLEAN",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "BOOLEAN_LITERAL",
  "ID"
  };
}

